/* pv/stages_gen.js — writes pv/stages.js, the PV stage table in the platform's STAGES format, from pv/index.html.
   PV is the one route whose stations live inside its page (MODULES + the no-picture twins + STAGE_NO), so the
   teacher page and room/routes.js had no table to read a station's NAME from. This script derives one; it is not
   a route module (no generators, no figs — PV still cannot be used in a room), only names.

     node pv/stages_gen.js           # rewrite pv/stages.js
     node pv/stages_gen.js --check   # exit 1 if pv/stages.js is stale (run by supabase/test/e2e_teacher_print.js)

   Re-run it whenever MODULES or STAGE_NO in pv/index.html change. Owner: platform owner. */
'use strict';
const fs = require('fs'), path = require('path'), vm = require('vm');
const DIR = __dirname, page = fs.readFileSync(path.join(DIR, 'index.html'), 'utf8');
const grab = re => { const m = page.match(re); if (!m) throw new Error('pv/index.html: block not found ' + re); return m[0]; };
const src = [grab(/const MODULES = \[[\s\S]*?\n\];/), grab(/const ADDSUB = new Set\([\s\S]*?\]\);/), grab(/const NOFIG = new Set\(\);[\s\S]*?\n}\n/), grab(/const STAGE_NO = \{[\s\S]*?\n\};/)].join('\n');
const c = {}; vm.createContext(c); vm.runInContext(src + '\nglobalThis.__R = { MODULES, STAGE_NO };', c);
const rows = [];
for (const m of c.__R.MODULES) for (const l of m.levels) { const n = c.__R.STAGE_NO[l.id]; if (!n) throw new Error('no station number for level ' + l.id); rows.push([n, m.name + ' · ' + l.name]); }
const nums = new Set(rows.map(r => r[0])); for (const k of Object.keys(c.__R.STAGE_NO)) if (!rows.some(r => r[0] === c.__R.STAGE_NO[k])) throw new Error('STAGE_NO has ' + k + ' but MODULES do not');
if (nums.size !== rows.length) throw new Error('duplicate station numbers');
rows.sort((a, b) => a[0] - b[0]);
const q = s => "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
const out = `/* pv/stages.js — GENERATED by pv/stages_gen.js from pv/index.html (MODULES + STAGE_NO). Do not edit: re-run
   \`node pv/stages_gen.js\` after changing PV's levels. Row: [id, Kazakh name, type, params, prereq, grade] — the
   platform's STAGES format, read by room/routes.js stageNames() so the teacher page can name a PV station.
   Names only: PV has no generator module, so it cannot be used in a challenge room. */
var STAGES = [
${rows.map(r => `  ['PV-${String(r[0]).padStart(2, '0')}', ${q(r[1])}, 'pv', {}, [], ''],`).join('\n')}
];
`;
const file = path.join(DIR, 'stages.js');
if (process.argv.includes('--check')) { const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : ''; if (cur !== out) { console.error('pv/stages.js is stale — run node pv/stages_gen.js'); process.exit(1); } console.log('pv/stages.js is current: ' + rows.length + ' stations'); }
else { fs.writeFileSync(file, out); console.log('wrote pv/stages.js: ' + rows.length + ' stations'); }
