/* wp/given.js — Берілгені (қысқаша жазу) for the templates whose bank row has no `given` of its own
   (WP-02…WP-13; WP-01 and the eight grade-1 templates carry it inside bank.js).
   Owner, 2026-10-06: «L3 — the child fills in the knowns first, then computes» — so every template needs a knowns block.
   Shape is the bank's: given:[{label,val,unit}], qline:{label,unit}. `val` is a variable of the template's vars
   (or a short expression), labels/units are filled with the same {placeholders} as the stem.
   A relation line («3 есе кем», «5 артық») carries the factor/difference as its value and the relation as its unit.
   generate.js merges this table into the drawn item when the bank row has none. Hand-authored — not from the Excel bank. */
'use strict';
const GIVEN={
 /* ── WP-02: change / start unknown ── */
 'TP-02-01':{given:[{label:'Бастапқыда',val:'a',unit:'{item}'},{label:'Болды',val:'c',unit:'{item}'}],qline:{label:'Қосылды',unit:'{item}'}},
 'TP-02-04':{given:[{label:'Бастапқыда',val:'a',unit:'{item}'},{label:'Қалды',val:'c',unit:'{item}'}],qline:{label:'Алынды',unit:'{item}'}},
 'TP-02-02':{given:[{label:'Берді',val:'b',unit:'{item}'},{label:'Қалды',val:'c',unit:'{item}'}],qline:{label:'Бастапқыда',unit:'{item}'}},
 'TP-02-05':{given:[{label:'Берілді',val:'b',unit:'{item}'},{label:'Болды',val:'c',unit:'{item}'}],qline:{label:'Бастапқыда',unit:'{item}'}},
 'TP-02-06':{given:[{label:'Алды',val:'b',unit:'{item}'},{label:'Болды',val:'c',unit:'{item}'}],qline:{label:'Бастапқыда (x)',unit:'{item}'}},
 'TP-02-07':{given:[{label:'Бастапқыда',val:'a',unit:'{item}'},{label:'Болды',val:'c',unit:'{item}'}],qline:{label:'Қосылды',unit:'{item}'}},
 'TP-02-03':{given:[{label:'Болды',val:'a',unit:'{item}'},{label:'Қалды',val:'c',unit:'{item}'}],qline:{label:'Берді',unit:'{item}'}},
 'TP-02-08':{given:[{label:'Арттырды',val:'k',unit:''},{label:'Шықты',val:'r',unit:''}],qline:{label:'Ойлаған сан',unit:''}},
 'TP-02-09':{given:[{label:'Кемітті',val:'k',unit:''},{label:'Шықты',val:'r',unit:''}],qline:{label:'Ойлаған сан',unit:''}},
 'TP-02-10':{given:[{label:'Сатылды',val:'b',unit:'{item}'},{label:'Қалды',val:'c',unit:'{item}'}],qline:{label:'Алғашында',unit:'{item}'}},
 'TP-02-11':{given:[{label:'Бастапқыда',val:'a',unit:'кітап'},{label:'Болды',val:'c',unit:'кітап'}],qline:{label:'Әкелінді',unit:'кітап'}},
 /* ── WP-03: equal groups ── */
 'TP-03-01':{given:[{label:'{box} саны',val:'n',unit:''},{label:'1 {box_LOC}',val:'k',unit:'{item}'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-03-04':{given:[{label:'{box} саны',val:'n',unit:''},{label:'1 {box_LOC}',val:'k',unit:'{item}'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-03-05':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'Бала саны',val:'n',unit:''}],qline:{label:'1 балаға',unit:'{item}'}},
 'TP-03-06':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'1 {box_DAT}',val:'k',unit:'{item}'}],qline:{label:'{box} саны',unit:''}},
 'TP-03-02':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'Бала саны',val:'n',unit:''}],qline:{label:'1 балаға',unit:'{item}'}},
 'TP-03-03':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'1 {box_DAT}',val:'k',unit:'{item}'}],qline:{label:'{box} саны',unit:''}},
 'TP-03-07':{given:[{label:'Күн саны',val:'m',unit:''},{label:'1 күнде',val:'k',unit:'есеп'}],qline:{label:'Барлығы',unit:'есеп'}},
 'TP-03-08':{given:[{label:'1 көйлек',val:'k',unit:'м'},{label:'Көйлек саны',val:'n',unit:''}],qline:{label:'Барлығы',unit:'м'}},
 'TP-03-10':{given:[{label:'Барлығы',val:'total',unit:'қарындаш'},{label:'Қорап саны',val:'n',unit:''}],qline:{label:'1 қорапқа',unit:'қарындаш'}},
 'TP-03-11':{given:[{label:'1 {box_LOC}',val:'k',unit:'{item}'},{label:'{box} саны',val:'n',unit:''}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-03-12':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'{box} саны',val:'n',unit:''}],qline:{label:'1 {box_DAT}',unit:'{item}'}},
 'TP-03-13':{given:[{label:'1 рет',val:'k',unit:'{item}'},{label:'Рет саны',val:'m',unit:''}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-03-14':{given:[{label:'{box} саны',val:'n',unit:''},{label:'1 {box_LOC}',val:'k',unit:'{item}'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-03-15':{given:[{label:'Барлығы',val:'total',unit:'{item}'},{label:'1 {box_DAT}',val:'k',unit:'{item}'}],qline:{label:'{box} саны',unit:''}},
 /* ── WP-04: times as many ── */
 'TP-04-01':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item}'}],qline:{label:'Неше есе артық',unit:'есе'}},
 'TP-04-02':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'n',unit:'есе артық'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-04-05':{given:[{label:'{name1}',val:'b',unit:'{item}'},{label:'{name2}',val:'n',unit:'есе кем'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-04-03':{given:[{label:'{name1}',val:'b',unit:'{item}'},{label:'{name2}',val:'n',unit:'есе кем'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-04-06':{given:[{label:'{name1}',val:'a',unit:'жас'},{label:'{name2}',val:'n',unit:'есе үлкен'}],qline:{label:'{name2}',unit:'жас'}},
 'TP-04-07':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item}'}],qline:{label:'Неше есе артық',unit:'есе'}},
 'TP-04-08':{given:[{label:'{box1}',val:'b',unit:'{item}'},{label:'{box2}',val:'a',unit:'{item}'}],qline:{label:'Неше есе кем',unit:'есе'}},
 'TP-04-04':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'n',unit:'есе артық'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-04-09':{given:[{label:'{name1}',val:'b',unit:'{item}'},{label:'{name2}',val:'n',unit:'есе кем'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-04-10':{given:[{label:'Алма ағашы',val:'a',unit:''},{label:'Алмұрт ағашы',val:'n',unit:'есе көп'}],qline:{label:'Алмұрт ағашы',unit:''}},
 'TP-04-11':{given:[{label:'{name1}',val:'a',unit:'теңге'},{label:'{name2}',val:'b',unit:'теңге'}],qline:{label:'Неше есе артық',unit:'есе'}},
 /* ── WP-05: two operations ── */
 'TP-05-01':{given:[{label:'Болды',val:'a',unit:'{item}'},{label:'Берді',val:'b',unit:'{item}'},{label:'Алды',val:'c',unit:'{item}'}],qline:{label:'Қазір',unit:'{item}'}},
 'TP-05-05':{given:[{label:'Болды',val:'a',unit:'{item}'},{label:'Келді',val:'b',unit:'{item}'},{label:'Кетті',val:'c',unit:'{item}'}],qline:{label:'Қалды',unit:'{item}'}},
 'TP-05-02':{given:[{label:'{box} саны',val:'n',unit:''},{label:'1 {box_LOC}',val:'k',unit:'{item}'},{label:'Тағы',val:'c',unit:'{item}'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-05-06':{given:[{label:'Барлығы',val:'t',unit:'зат'},{label:'{item1}',val:'a',unit:''},{label:'{item2}',val:'b',unit:''}],qline:{label:'{item3}',unit:''}},
 'TP-05-07':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item} артық'}],qline:{label:'Екеуі бірге',unit:'{item}'}},
 'TP-05-08':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item} кем'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-05-09':{given:[{label:'Болды',val:'a',unit:'теңге'},{label:'{good1}',val:'p1',unit:'теңге'},{label:'{good2}',val:'p2',unit:'теңге'}],qline:{label:'Қалды',unit:'теңге'}},
 'TP-05-03':{given:[{label:'{box} ({item1})',val:'n1',unit:''},{label:'1 {box_LOC}',val:'k1',unit:'{item1}'},{label:'{box2} ({item2})',val:'n2',unit:''},{label:'1 {box2_LOC}',val:'k2',unit:'{item2}'}],qline:{label:'Барлығы',unit:'зат'}},
 'TP-05-04':{given:[{label:'Ересек',val:'n1',unit:'адам'},{label:'1 ересек',val:'p1',unit:'теңге'},{label:'Бала',val:'n2',unit:'адам'},{label:'1 бала',val:'p2',unit:'теңге'}],qline:{label:'Барлығы',unit:'теңге'}},
 'TP-05-10':{given:[{label:'{box} саны',val:'n',unit:''},{label:'1 {box_LOC}',val:'k',unit:'{item}'},{label:'Сатылды',val:'c',unit:'{item}'}],qline:{label:'Қалды',unit:'{item}'}},
 'TP-05-11':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item}'},{label:'{box} саны',val:'n',unit:''}],qline:{label:'1 {box_DAT}',unit:'{item}'}},
 'TP-05-12':{given:[{label:'1-орам',val:'a',unit:'м'},{label:'2-орам',val:'b',unit:'м кем'},{label:'1 көйлек',val:'k',unit:'м'}],qline:{label:'Көйлек саны',unit:''}},
 'TP-05-13':{given:[{label:'1-күн',val:'a',unit:'кг'},{label:'2-күн',val:'b',unit:'кг артық'},{label:'3-күн',val:'c',unit:'кг'}],qline:{label:'Барлығы',unit:'кг'}},
 /* ── WP-06: chained comparison ── */
 'TP-06-01':{given:[{label:'1-{box}',val:'a',unit:'{item}'},{label:'2-{box}',val:'b',unit:'артық'},{label:'3-{box}',val:'c',unit:'кем'}],qline:{label:'3-{box}',unit:'{item}'}},
 'TP-06-02':{given:[{label:'1-{box}',val:'a',unit:'{item}'},{label:'2-{box}',val:'b',unit:'артық'},{label:'3-{box}',val:'c',unit:'кем'}],qline:{label:'3-{box}',unit:'{item}'}},
 'TP-06-03':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item} артық'},{label:'{name3}',val:'c',unit:'{item} кем'}],qline:{label:'Үшеуі бірге',unit:'{item}'}},
 'TP-06-04':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item} артық'},{label:'{name3}',val:'c',unit:'{item} кем'}],qline:{label:'Айырмасы',unit:'{item}'}},
 'TP-06-05':{given:[{label:'Барлығы',val:'t',unit:'адам'},{label:'Ер адамдар',val:'a',unit:''},{label:'Әйелдер',val:'n',unit:'есе артық'}],qline:{label:'Балалар',unit:''}},
 'TP-06-06':{given:[{label:'{name1}',val:'a',unit:'есеп'},{label:'{name2}',val:'b',unit:'есеп артық'},{label:'{name3}',val:'c',unit:'есеп артық'}],qline:{label:'{name3}',unit:'есеп'}},
 'TP-06-07':{given:[{label:'1-қойма',val:'a',unit:'т'},{label:'2-қойма',val:'b',unit:'т кем'},{label:'3-қойма',val:'c',unit:'т артық'}],qline:{label:'3-қойма',unit:'т'}},
 'TP-06-08':{given:[{label:'{name1}',val:'a',unit:'{item}'},{label:'{name2}',val:'b',unit:'{item}'},{label:'Берді',val:'c',unit:'{item}'}],qline:{label:'Айырмасы',unit:'{item}'}},
 /* ── WP-07: price · quantity · cost ── */
 'TP-07-01':{given:[{label:'Бағасы',val:'p',unit:'теңге'},{label:'Саны',val:'n',unit:''}],qline:{label:'Құны',unit:'теңге'}},
 'TP-07-05':{given:[{label:'Бағасы',val:'p',unit:'теңге'},{label:'Ақшасы',val:'total',unit:'теңге'}],qline:{label:'Саны',unit:'{good}'}},
 'TP-07-02':{given:[{label:'Бағасы',val:'p',unit:'теңге'},{label:'Құны',val:'total',unit:'теңге'}],qline:{label:'Саны',unit:'{good}'}},
 'TP-07-03':{given:[{label:'Саны',val:'n',unit:'{good}'},{label:'Құны',val:'total',unit:'теңге'}],qline:{label:'Бағасы',unit:'теңге'}},
 'TP-07-06':{given:[{label:'Бағасы',val:'p',unit:'теңге'},{label:'Саны',val:'n',unit:''},{label:'Берді',val:'m',unit:'теңге'}],qline:{label:'Қайтарым',unit:'теңге'}},
 'TP-07-07':{given:[{label:'{good1}',val:'n1',unit:''},{label:'{good1} бағасы',val:'p1',unit:'теңге'},{label:'{good2}',val:'n2',unit:''},{label:'{good2} бағасы',val:'p2',unit:'теңге'}],qline:{label:'Барлығы',unit:'теңге'}},
 'TP-07-04':{given:[{label:'1-рет саны',val:'n1',unit:'{good}'},{label:'1-рет құны',val:'total1',unit:'теңге'},{label:'2-рет саны',val:'n2',unit:'{good}'}],qline:{label:'2-рет құны',unit:'теңге'}},
 'TP-07-08':{given:[{label:'{good1} бағасы',val:'p1',unit:'теңге'},{label:'{good1} құны',val:'t1',unit:'теңге'},{label:'{good2} бағасы',val:'p2',unit:'теңге'}],qline:{label:'{good2} құны',unit:'теңге'}},
 'TP-07-09':{given:[{label:'{good1} бағасы',val:'p1',unit:'теңге'},{label:'{good1} саны',val:'n1',unit:''},{label:'{good2} бағасы',val:'p2',unit:'теңге'}],qline:{label:'{good2} саны',unit:''}},
 'TP-07-10':{given:[{label:'{good} саны',val:'n',unit:''},{label:'{good2} бағасы',val:'p2',unit:'теңге'},{label:'Барлығы',val:'t',unit:'теңге'}],qline:{label:'{good} бағасы',unit:'теңге'}},
 'TP-07-11':{given:[{label:'{good1}',val:'n1',unit:''},{label:'{good1} бағасы',val:'p1',unit:'теңге'},{label:'{good2}',val:'n2',unit:''},{label:'{good2} бағасы',val:'p2',unit:'теңге'}],qline:{label:'Барлығы',unit:'теңге'}},
 /* ── WP-08: sum & multiple / sum & difference ── */
 'TP-08-01':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'{name1}',val:'n',unit:'есе артық'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-08-02':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'{name1}',val:'d',unit:'{item} артық'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-08-03':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'{name1}',val:'n',unit:'есе артық'}],qline:{label:'{name1}',unit:'{item}'}},
 'TP-08-04':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'{name1}',val:'d',unit:'{item} артық'}],qline:{label:'{name1}',unit:'{item}'}},
 'TP-08-05':{given:[{label:'Есесі',val:'n',unit:'есе'},{label:'Айырмасы',val:'d',unit:'{item}'}],qline:{label:'{name2}',unit:'{item}'}},
 'TP-08-06':{given:[{label:'Барлығы',val:'t',unit:'т'},{label:'1-қойма',val:'n',unit:'есе артық'}],qline:{label:'2-қойма',unit:'т'}},
 'TP-08-07':{given:[{label:'Барлығы',val:'t',unit:'оқушы'},{label:'1-сынып',val:'d',unit:'оқушы артық'}],qline:{label:'1-сынып',unit:'оқушы'}},
 'TP-08-08':{given:[{label:'Есесі',val:'n',unit:'есе'},{label:'Айырмасы',val:'d',unit:'жас'}],qline:{label:'{name2}',unit:'жас'}},
 'TP-08-09':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'2-{box}',val:'d1',unit:'артық'},{label:'3-{box}',val:'d2',unit:'артық'}],qline:{label:'1-{box}',unit:'{item}'}},
 /* ── WP-09: speed · time · distance, rate · time · work ── */
 'TP-09-01':{given:[{label:'Жылдамдығы',val:'v',unit:'км/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Жолы',unit:'км'}},
 'TP-09-04':{given:[{label:'Өнімділігі',val:'v',unit:'{worker_unit}/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Жұмысы',unit:'{worker_unit}'}},
 'TP-09-02':{given:[{label:'Уақыты',val:'t',unit:'сағ'},{label:'Жолы',val:'s',unit:'км'}],qline:{label:'Жылдамдығы',unit:'км/сағ'}},
 'TP-09-03':{given:[{label:'Жылдамдығы',val:'v',unit:'км/сағ'},{label:'Жолы',val:'s',unit:'км'}],qline:{label:'Уақыты',unit:'сағ'}},
 'TP-09-05':{given:[{label:'Уақыты',val:'t',unit:'сағ'},{label:'Жұмысы',val:'A',unit:'{worker_unit}'}],qline:{label:'Өнімділігі',unit:'{worker_unit}/сағ'}},
 'TP-09-06':{given:[{label:'Өнімділігі',val:'v',unit:'{worker_unit}/сағ'},{label:'Жұмысы',val:'A',unit:'{worker_unit}'}],qline:{label:'Уақыты',unit:'сағ'}},
 'TP-09-07':{given:[{label:'1-жылдамдық',val:'v1',unit:'км/сағ'},{label:'1-уақыт',val:'t1',unit:'сағ'},{label:'2-жылдамдық',val:'v2',unit:'км/сағ'},{label:'2-уақыт',val:'t2',unit:'сағ'}],qline:{label:'Барлық жол',unit:'км'}},
 'TP-09-08':{given:[{label:'Жолы',val:'s',unit:'км'},{label:'Уақыты',val:'t',unit:'сағ'},{label:'2-уақыт',val:'t2',unit:'сағ'}],qline:{label:'2-жол',unit:'км'}},
 'TP-09-09':{given:[{label:'Жолы',val:'s',unit:'км'},{label:'Уақыты',val:'t',unit:'сағ'},{label:'Арттырды',val:'dv',unit:'км/сағ'}],qline:{label:'Жаңа уақыт',unit:'сағ'}},
 'TP-09-10':{given:[{label:'1-ші',val:'v1',unit:'{worker1_unit}/сағ'},{label:'2-ші',val:'v2',unit:'{worker1_unit}/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Бірге',unit:'{worker1_unit}'}},
 /* ── WP-10: motion / joint work ── */
 'TP-10-01':{given:[{label:'1-жылдамдық',val:'v1',unit:'км/сағ'},{label:'2-жылдамдық',val:'v2',unit:'км/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Арақашықтық',unit:'км'}},
 'TP-10-02':{given:[{label:'Арақашықтық',val:'s',unit:'км'},{label:'1-жылдамдық',val:'v1',unit:'км/сағ'},{label:'2-жылдамдық',val:'v2',unit:'км/сағ'}],qline:{label:'Уақыты',unit:'сағ'}},
 'TP-10-03':{given:[{label:'1-жылдамдық',val:'v1',unit:'км/сағ'},{label:'2-жылдамдық',val:'v2',unit:'км/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Арақашықтық',unit:'км'}},
 'TP-10-04':{given:[{label:'Жұмыс',val:'A',unit:'{worker_unit}'},{label:'1-ші',val:'v1',unit:'{worker_unit}/сағ'},{label:'2-ші',val:'v2',unit:'{worker_unit}/сағ'}],qline:{label:'Уақыты',unit:'сағ'}},
 'TP-10-05':{given:[{label:'Арақашықтық',val:'s',unit:'км'},{label:'Уақыты',val:'t',unit:'сағ'},{label:'1-жылдамдық',val:'v1',unit:'км/сағ'}],qline:{label:'2-жылдамдық',unit:'км/сағ'}},
 'TP-10-06':{given:[{label:'Велосипедші',val:'v2',unit:'км/сағ'},{label:'Мотоциклші',val:'v1',unit:'км/сағ'},{label:'Ерте шықты',val:'t0',unit:'сағ'}],qline:{label:'Қуып жетеді',unit:'сағ'}},
 'TP-10-07':{given:[{label:'1-құбыр',val:'t1',unit:'сағ'},{label:'2-құбыр',val:'t2',unit:'сағ'}],qline:{label:'Бірге',unit:'сағ'}},
 'TP-10-08':{given:[{label:'Меншікті жылдамдық',val:'v',unit:'км/сағ'},{label:'Ағыс жылдамдығы',val:'c',unit:'км/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Жолы',unit:'км'}},
 'TP-10-09':{given:[{label:'Меншікті жылдамдық',val:'v',unit:'км/сағ'},{label:'Ағыс жылдамдығы',val:'c',unit:'км/сағ'},{label:'Уақыты',val:'t',unit:'сағ'}],qline:{label:'Жолы',unit:'км'}},
 /* ── WP-11: fractions of a quantity (a fraction is written as «value /b бөлігі») ── */
 'TP-11-01':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'Бөлігі',val:'one',unit:'/{b} бөлігі'}],qline:{label:'Бөлігі',unit:'{item}'}},
 'TP-11-02':{given:[{label:'Бөлігі',val:'one',unit:'/{b} бөлігі'},{label:'Бұл',val:'k',unit:'{item}'}],qline:{label:'Барлығы',unit:'{item}'}},
 'TP-11-03':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'Бөлігі',val:'a',unit:'/{b} бөлігі'}],qline:{label:'Бөлігі',unit:'{item}'}},
 'TP-11-04':{given:[{label:'Оқыды',val:'a',unit:'/{b} бөлігі'},{label:'Бұл',val:'p',unit:'бет'}],qline:{label:'Барлығы',unit:'бет'}},
 'TP-11-05':{given:[{label:'Болды',val:'t',unit:'{item}'},{label:'Алынды',val:'one',unit:'/{b} бөлігі'}],qline:{label:'Қалды',unit:'{item}'}},
 'TP-11-06':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'Сатылды',val:'a',unit:'/{b} бөлігі'}],qline:{label:'Қалды',unit:'{item}'}},
 'TP-11-07':{given:[{label:'Барлығы',val:'t',unit:'бет'},{label:'1-күн',val:'a',unit:'/{b} бөлігі'},{label:'2-күн',val:'c',unit:'бет'}],qline:{label:'Қалды',unit:'бет'}},
 'TP-11-08':{given:[{label:'Сатылды',val:'one',unit:'/{b} бөлігі'},{label:'Бұл',val:'k',unit:'кг'}],qline:{label:'Қалды',unit:'кг'}},
 'TP-11-09':{given:[{label:'Барлығы',val:'t',unit:'есеп'},{label:'{name1}',val:'a',unit:'/{b} бөлігі'},{label:'{name2}',val:'c',unit:'/{d} бөлігі'}],qline:{label:'Айырмасы',unit:'есеп'}},
 /* ── WP-12: two sums / two differences ── */
 'TP-12-01':{given:[{label:'{item1}',val:'n1',unit:'жәшік'},{label:'{item2}',val:'n2',unit:'жәшік'},{label:'Барлығы',val:'t',unit:'кг'}],qline:{label:'{item1}',unit:'кг'}},
 'TP-12-02':{given:[{label:'Шалбар',val:'n1',unit:''},{label:'Көйлек',val:'n2',unit:''},{label:'Артық',val:'d',unit:'м'}],qline:{label:'1 зат',unit:'м'}},
 'TP-12-03':{given:[{label:'{item1}',val:'n1',unit:'жәшік'},{label:'{item2}',val:'n2',unit:'жәшік'},{label:'Барлығы',val:'t',unit:'теңге'}],qline:{label:'{item2}',unit:'теңге'}},
 'TP-12-04':{given:[{label:'{good1}',val:'n1',unit:''},{label:'{good2}',val:'n2',unit:''},{label:'Барлығы',val:'t',unit:'теңге'}],qline:{label:'{good1}',unit:'теңге'}},
 'TP-12-05':{given:[{label:'1-көлік',val:'n1',unit:'қап'},{label:'2-көлік',val:'n2',unit:'қап'},{label:'Артық',val:'d',unit:'кг'}],qline:{label:'1-көлік',unit:'кг'}},
 'TP-12-06':{given:[{label:'{name1}',val:'n1',unit:'{good}'},{label:'{name2}',val:'n2',unit:'{good}'},{label:'Артық',val:'d',unit:'теңге'}],qline:{label:'1 {good}',unit:'теңге'}},
 /* ── WP-13: percent ── */
 'TP-13-01':{given:[{label:'Барлығы',val:'t',unit:'{item}'},{label:'Пайызы',val:'p',unit:'%'}],qline:{label:'Бөлігі',unit:'{item}'}},
 'TP-13-02':{given:[{label:'Барлығы',val:'t',unit:'оқушы'},{label:'Қыздар',val:'p',unit:'%'}],qline:{label:'Қыздар',unit:'оқушы'}},
 'TP-13-03':{given:[{label:'Бағасы',val:'t',unit:'теңге'},{label:'Төмендеді',val:'p',unit:'%'}],qline:{label:'Жаңа бағасы',unit:'теңге'}},
 'TP-13-04':{given:[{label:'Оқыды',val:'p',unit:'%'},{label:'Бұл',val:'k',unit:'бет'}],qline:{label:'Барлығы',unit:'бет'}},
 'TP-13-05':{given:[{label:'Болды',val:'t',unit:'кг'},{label:'Сатылды',val:'p',unit:'%'}],qline:{label:'Қалды',unit:'кг'}},
 'TP-13-06':{given:[{label:'Барлығы',val:'t',unit:'оқушы'},{label:'Ұлдар',val:'k',unit:'оқушы'}],qline:{label:'Ұлдар',unit:'%'}},
 'TP-13-07':{given:[{label:'Бұрын',val:'t',unit:'бөлшек'},{label:'Артты',val:'p',unit:'%'}],qline:{label:'Енді',unit:'бөлшек'}},
 'TP-13-08':{given:[{label:'Бағасы',val:'t',unit:'теңге'},{label:'1-төмендеу',val:'p',unit:'%'},{label:'2-төмендеу',val:'q',unit:'%'}],qline:{label:'Соңғы бағасы',unit:'теңге'}},
 'TP-13-09':{given:[{label:'Салым',val:'t',unit:'теңге'},{label:'Өсім',val:'p',unit:'%'}],qline:{label:'Бір жылдан кейін',unit:'теңге'}},
};
