/* wp/icons.js — the little picture inside each station on the route map (core/map.js).
   ICONS[stageId] = SVG markup drawn around (0,0), about 24×24. `currentColor` follows the station state.
   Each icon is a miniature of the figure that stage actually uses, so a child recognises the stop. Owner: Nurdaulet. */
const ICONS={
 'WP-01':'<circle cx="-8" cy="0" r="4.4" fill="currentColor"/><circle cx="8" cy="0" r="4.4" fill="currentColor" opacity=".45"/><path d="M-1,0 h4 M1,-2 v4" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>',
 'WP-02':'<rect x="-12" y="-6" width="24" height="12" rx="2" fill="none" stroke="currentColor" stroke-width="1.8"/><rect x="-12" y="-6" width="10" height="12" fill="currentColor" opacity=".5"/><text x="5" y="4" text-anchor="middle" font-family="Fredoka,sans-serif" font-weight="600" font-size="11" fill="currentColor">?</text>',
 'WP-03':'<g fill="currentColor"><circle cx="-8" cy="-6" r="2.6"/><circle cx="0" cy="-6" r="2.6"/><circle cx="8" cy="-6" r="2.6"/><circle cx="-8" cy="1" r="2.6"/><circle cx="0" cy="1" r="2.6"/><circle cx="8" cy="1" r="2.6"/><circle cx="-8" cy="8" r="2.6" opacity=".4"/><circle cx="0" cy="8" r="2.6" opacity=".4"/><circle cx="8" cy="8" r="2.6" opacity=".4"/></g>',
 'WP-04':'<rect x="-12" y="-9" width="7" height="6" rx="1.5" fill="currentColor"/><rect x="-12" y="2" width="22" height="6" rx="1.5" fill="currentColor" opacity=".5"/><text x="10" y="-4" text-anchor="middle" font-family="Fredoka,sans-serif" font-weight="600" font-size="9" fill="currentColor">×3</text>',
 'WP-05':'<rect x="-12" y="-10" width="16" height="5" rx="1.5" fill="currentColor"/><rect x="-12" y="-2" width="10" height="5" rx="1.5" fill="currentColor" opacity=".65"/><rect x="-12" y="6" width="22" height="5" rx="1.5" fill="currentColor" opacity=".4"/>',
 'WP-06':'<rect x="-12" y="-9" width="22" height="6" rx="1.5" fill="currentColor"/><rect x="-12" y="2" width="13" height="6" rx="1.5" fill="currentColor" opacity=".5"/><path d="M1,2 v6 M10,-3 v11 M1,8 h9" stroke="currentColor" stroke-width="1.2" fill="none"/>',
 'WP-07':'<text x="0" y="6" text-anchor="middle" font-family="Fredoka,sans-serif" font-weight="600" font-size="17" fill="currentColor">₸</text>',
 'WP-08':'<rect x="-12" y="-9" width="15" height="6" rx="1.5" fill="currentColor"/><rect x="-12" y="1" width="22" height="6" rx="1.5" fill="currentColor" opacity=".5"/><path d="M12,-9 q3,0 3,4 q0,4 3,4 q-3,0 -3,4 q0,4 -3,4" fill="none" stroke="currentColor" stroke-width="1.3" transform="translate(-2,0)"/>',
 'WP-09':'<line x1="-12" y1="2" x2="9" y2="2" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"/><path d="M12,2 L5,-2.5 L5,6.5Z" fill="currentColor"/><text x="-2" y="-5" text-anchor="middle" font-family="Fredoka,sans-serif" font-weight="600" font-size="9" fill="currentColor">v·t</text>',
 'WP-10':'<line x1="-12" y1="4" x2="12" y2="4" stroke="currentColor" stroke-width="1.6"/><path d="M-11,-4 L-1,-4 M-4,-7.5 L-1,-4 L-4,-.5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/><path d="M11,-4 L1,-4 M4,-7.5 L1,-4 L4,-.5" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" opacity=".55"/>',
 'WP-11':'<circle r="11" fill="none" stroke="currentColor" stroke-width="1.8"/><path d="M0,0 L0,-11 A11,11 0 0,1 0,11Z" fill="currentColor" opacity=".55"/><line x1="0" y1="-11" x2="0" y2="11" stroke="currentColor" stroke-width="1.2"/>',
 'WP-12':'<rect x="-11" y="-9" width="22" height="18" rx="2" fill="none" stroke="currentColor" stroke-width="1.6"/><line x1="-11" y1="-1" x2="11" y2="-1" stroke="currentColor" stroke-width="1.2"/><line x1="0" y1="-9" x2="0" y2="9" stroke="currentColor" stroke-width="1.2"/><circle cx="-5.5" cy="-5" r="1.8" fill="currentColor"/><circle cx="5.5" cy="4" r="1.8" fill="currentColor" opacity=".5"/>',
 'WP-13':'<text x="0" y="6" text-anchor="middle" font-family="Fredoka,sans-serif" font-weight="600" font-size="16" fill="currentColor">%</text>',
};
